### ISSUE TITLE
deal with "IndexError" (ask_ib.py)

### ISSUE THREAD

**Issue by ltaulell** [ltaulell/HPC_toolset#1]
when a node is not responding, return list is empty. Try/Except IndexError pass?

**Comment by ltaulell** [comment]
example traceback:
[...]
c6420node017
c6420node018
2020-02-21 14:18:11,950 WARNING: terminated: <SshProcess('ibv_devinfo | grep fw_ver', Host('c6420node018'), connection_params={'user': 'root'}, name=ibv_devinfo | grep fw_ver, started=True, start_date=2020-02-21 14:18:08+01:00, ended=True, end_date=2020-02-21 14:18:11+01:00, killed=False, error=False, error_reason=None, timeouted=False, expect_fail=False, write_error=False, exit_code=65280, ok=False, pid=42268, real cmd=('ssh', '-tt', '-o', 'BatchMode=yes', '-o', 'PasswordAuthentication=no', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ConnectTimeout=20', '-o', 'User=root', 'c6420node018', 'ibv_devinfo | grep fw_ver'))>
stdout:

stderr:
ssh: connect to host c6420node018 port 22: No route to host

Traceback (most recent call last):
  File "/home/ltaulell/tools4psmn/pytools/ask_infiniband.py", line 102, in <module>
    main()
  File "/home/ltaulell/tools4psmn/pytools/ask_infiniband.py", line 49, in main
    res_fw = ask_node(cmd_fw, node, debug)
  File "/home/ltaulell/tools4psmn/pytools/ask_infiniband.py", line 97, in ask_node
    return str(process.stdout.split()[-1])
IndexError: list index out of range
